/* oxlint-disable jsx-a11y/prefer-tag-over-role -- the source picker uses custom two-axis and one-axis visual tracks. */
import { useEffect, useRef, useState, type PointerEvent as ReactPointerEvent } from 'react'
import { useTranslation } from 'react-i18next'

import tinycolor, { type ColorFormats } from 'tinycolor2'

import NeedleIcon from '~icons/icon-park-outline/needle'

const RECENT_COLORS_KEY = 'RECENT_COLORS'
// Byte-identical to the 16 x 16 canvas generated by PPTist's Checkboard.vue
// for #fff / #e6e6e6 eight-pixel squares.
const CHECKBOARD = 'url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAOklEQVR4AeySuQ0AMAwCkbfw/rvBGM4GpHARiiBdi8RTJMcxFxWW+gZAQAfdDYckOAIiLI+YsMLzCAcAAP//0FHUVgAAAAZJREFUAwBpAlWJoGCVHAAAAABJRU5ErkJggg==)'
const themeColors = ['#000000', '#ffffff', '#eeece1', '#1e497b', '#4e81bb', '#e2534d', '#9aba60', '#8165a0', '#47acc5', '#f9974c']
const standardColors = ['#c21401', '#ff1e02', '#ffc12a', '#ffff3a', '#90cf5b', '#00af57', '#00afee', '#0071be', '#00215f', '#72349d']
const presetColorConfig = [
  ['#7f7f7f', '#f2f2f2'], ['#0d0d0d', '#808080'], ['#1c1a10', '#ddd8c3'],
  ['#0e243d', '#c6d9f0'], ['#233f5e', '#dae5f0'], ['#632623', '#f2dbdb'],
  ['#4d602c', '#eaf1de'], ['#3f3150', '#e6e0ec'], ['#1e5867', '#d9eef3'],
  ['#99490f', '#fee9da'],
] as const

const gradient = (start: string, end: string) => {
  const startColor = tinycolor(start).toRgb()
  const endColor = tinycolor(end).toRgb()
  return Array.from({ length: 5 }, (_, index) => tinycolor({
    r: startColor.r + ((endColor.r - startColor.r) / 5) * index,
    g: startColor.g + ((endColor.g - startColor.g) / 5) * index,
    b: startColor.b + ((endColor.b - startColor.b) / 5) * index,
  }).toRgbString())
}
const presetColors = presetColorConfig.map(([end, start]) => gradient(start, end))
const rgbaString = (rgba: ColorFormats.RGBA) => `rgba(${rgba.r},${rgba.g},${rgba.b},${rgba.a})`

function PickerSwatch({ color, onClick }: { color: string; onClick: () => void }) {
  const rgb = tinycolor(color).toRgb()
  const white = rgb.r === 255 && rgb.g === 255 && rgb.b === 255 && rgb.a === 1
  return (
    <button
      aria-label={`Select color ${color}`}
      className={`mona-color-picker-swatch${white ? ' is-white' : ''}`}
      onClick={onClick}
      style={{ background: color }}
      type="button"
    />
  )
}

export function EditorColorPicker({
  onChange,
  value = '#ffffff',
}: {
  onChange: (value: string) => void
  value?: string
}) {
  const { t } = useTranslation()
  const [hue, setHue] = useState(-1)
  const [recentColors, setRecentColors] = useState<string[]>(() => {
    try {
      return JSON.parse(localStorage.getItem(RECENT_COLORS_KEY) || '[]') as string[]
    }
    catch {
      return []
    }
  })
  const recentTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null)
  const saturationThrottleRef = useRef(0)
  const color = tinycolor(value).toRgb()
  const hsv = tinycolor(color).toHsv()
  const currentHue = hue === -1 ? hsv.h : hue

  useEffect(() => () => {
    if (recentTimerRef.current) clearTimeout(recentTimerRef.current)
  }, [])

  const remember = (next: ColorFormats.RGBA) => {
    if (recentTimerRef.current) clearTimeout(recentTimerRef.current)
    recentTimerRef.current = setTimeout(() => {
      const nextColor = tinycolor(next).toRgbString()
      setRecentColors(current => {
        if (current.includes(nextColor)) return current
        const updated = [nextColor, ...current].slice(0, 10)
        localStorage.setItem(RECENT_COLORS_KEY, JSON.stringify(updated))
        return updated
      })
    }, 300)
  }

  const emitRGBA = (next: ColorFormats.RGBA) => {
    onChange(rgbaString(next))
    remember(next)
  }

  const trackPointer = (
    event: ReactPointerEvent<HTMLElement>,
    update: (clientX: number, clientY: number, rect: { height: number; left: number; top: number; width: number }) => void,
  ) => {
    event.preventDefault()
    const target = event.currentTarget
    const bounds = target.getBoundingClientRect()
    const rect = {
      height: target.clientHeight,
      left: bounds.left,
      top: bounds.top,
      width: target.clientWidth,
    }
    const move = (pointer: PointerEvent) => update(pointer.clientX, pointer.clientY, rect)
    const stop = () => {
      window.removeEventListener('pointermove', move)
      window.removeEventListener('pointerup', stop)
    }
    update(event.clientX, event.clientY, rect)
    window.addEventListener('pointermove', move)
    window.addEventListener('pointerup', stop, { once: true })
  }

  const selectPreset = (next: string) => {
    setHue(tinycolor(next).toHsl().h)
    onChange(next)
  }

  const customEyeDropper = async () => {
    const target = document.querySelector<HTMLElement>('.mona-editor-stage')
    if (!target) return

    const mask = document.createElement('div')
    mask.className = 'mona-color-picker-eyedropper-mask'
    mask.style.cssText = 'position: fixed; top: 0; left: 0; bottom: 0; right: 0; z-index: 9999; cursor: wait;'
    document.body.append(mask)

    const colorBlock = document.createElement('div')
    colorBlock.className = 'mona-color-picker-eyedropper-preview'
    colorBlock.style.cssText = 'position: absolute; top: -100px; left: -100px; width: 16px; height: 16px; border: 1px solid #000; z-index: 999;'
    mask.append(colorBlock)

    const { left, top, width, height } = target.getBoundingClientRect()
    const cleanupMask = () => {
      if (mask.parentNode) mask.remove()
    }

    try {
      const { toCanvas } = await import('html-to-image')
      const canvas = await toCanvas(target, {
        canvasHeight: height,
        canvasWidth: width,
        filter: node => {
          if (!(node instanceof HTMLElement)) return true
          if (node.tagName.toUpperCase() === 'FOREIGNOBJECT') return false
          return !node.classList.contains('operate')
            && !node.classList.contains('mona-selection-overlay')
            && !node.classList.contains('mona-editor-selection-layer')
        },
        fontEmbedCSS: '',
        height,
        pixelRatio: 1,
        width,
      })
      canvas.className = 'mona-color-picker-eyedropper-canvas'
      canvas.style.cssText = `position: absolute; top: ${top}px; left: ${left}px; cursor: crosshair;`
      mask.style.cursor = 'default'
      mask.append(canvas)
      const context = canvas.getContext('2d')
      if (!context) {
        cleanupMask()
        return
      }

      let currentColor = ''
      const handlePointerMove = (event: PointerEvent) => {
        const mouseX = Math.min(width - 1, Math.max(0, event.clientX - left))
        const mouseY = Math.min(height - 1, Math.max(0, event.clientY - top))
        const [r, g, b, a] = context.getImageData(mouseX, mouseY, 1, 1).data
        currentColor = `rgba(${r}, ${g}, ${b}, ${(a! / 255).toFixed(2)})`
        colorBlock.style.left = `${event.clientX + 10}px`
        colorBlock.style.top = `${event.clientY + 10}px`
        colorBlock.style.backgroundColor = currentColor
      }
      const handlePointerLeave = () => {
        currentColor = ''
        colorBlock.style.left = '-100px'
        colorBlock.style.top = '-100px'
        colorBlock.style.backgroundColor = ''
      }
      const handlePointerDown = (event: PointerEvent) => {
        if (currentColor && event.button === 0) {
          const next = tinycolor(currentColor)
          setHue(next.toHsl().h)
          emitRGBA(next.toRgb())
        }
        canvas.removeEventListener('pointermove', handlePointerMove)
        canvas.removeEventListener('pointerleave', handlePointerLeave)
        window.removeEventListener('pointerdown', handlePointerDown)
        cleanupMask()
      }
      canvas.addEventListener('pointermove', handlePointerMove)
      canvas.addEventListener('pointerleave', handlePointerLeave)
      window.addEventListener('pointerdown', handlePointerDown)
    }
    catch {
      cleanupMask()
      window.dispatchEvent(new CustomEvent('mona:notice', {
        detail: { text: t('foundation.editor.colorPicker.eyedropperFailed'), type: 'error' },
      }))
    }
  }

  const openEyeDropper = async () => {
    const EyeDropperConstructor = (window as typeof window & {
      EyeDropper?: new () => { open: () => Promise<{ sRGBHex: string }> }
    }).EyeDropper
    if (!EyeDropperConstructor) {
      await customEyeDropper()
      return
    }
    window.dispatchEvent(new CustomEvent('mona:notice', {
      detail: { text: t('foundation.editor.colorPicker.eyedropperActive'), type: 'success' },
    }))
    try {
      const result = await new EyeDropperConstructor().open()
      const next = tinycolor(result.sRGBHex)
      setHue(next.toHsl().h)
      emitRGBA(next.toRgb())
    }
    catch {
      // Cancelling the native picker is not an editor error.
    }
    finally {
      window.dispatchEvent(new CustomEvent('mona:notice', { detail: null }))
    }
  }

  return (
    <div className="mona-color-picker">
      <div className="mona-color-picker-saturation-wrap">
        <div
          aria-label="Color saturation and brightness"
          className="mona-color-picker-saturation"
          onPointerDown={event => trackPointer(event, (x, y, rect) => {
            const now = performance.now()
            if (now - saturationThrottleRef.current < 20) return
            saturationThrottleRef.current = now
            const saturation = Math.min(1, Math.max(0, (x - rect.left) / rect.width))
            const brightness = Math.min(1, Math.max(0, 1 - ((y - rect.top) / rect.height)))
            const next = tinycolor({ h: currentHue, s: saturation, v: brightness, a: color.a }).toRgb()
            setHue(currentHue)
            emitRGBA(next)
          })}
          aria-valuemax={100}
          aria-valuemin={0}
          aria-valuenow={Math.round(hsv.s * 100)}
          role="slider"
          style={{ background: `hsl(${currentHue}, 100%, 50%)` }}
          tabIndex={0}
        >
          <span className="mona-color-picker-saturation-white" />
          <span className="mona-color-picker-saturation-black" />
          <span className="mona-color-picker-saturation-pointer" style={{ left: `${hsv.s * 100}%`, top: `${101 - (hsv.v * 100)}%` }}><span className="mona-color-picker-saturation-circle" /></span>
        </div>
      </div>

      <div className="mona-color-picker-controls">
        <div className="mona-color-picker-current" style={{ backgroundImage: CHECKBOARD }}>
          <span style={{ background: rgbaString(color) }} />
        </div>
        <div className="mona-color-picker-sliders">
          <div className="mona-color-picker-hue-wrap">
            <div className="mona-color-picker-hue">
              <div
                aria-label="Color hue"
                className="mona-color-picker-hue-container"
                onPointerDown={event => trackPointer(event, (x, _y, rect) => {
                  const nextHue = Math.min(360, Math.max(0, ((x - rect.left) / rect.width) * 360))
                  setHue(nextHue)
                  emitRGBA(tinycolor({ ...tinycolor(color).toHsl(), h: nextHue }).toRgb())
                })}
                aria-valuemax={360}
                aria-valuemin={0}
                aria-valuenow={Math.round(currentHue)}
                role="slider"
                tabIndex={0}
              >
                <span className="mona-color-picker-hue-pointer" style={{ left: `${currentHue * 100 / 360}%` }}><span className="mona-color-picker-hue-picker" /></span>
              </div>
            </div>
          </div>
          <div className="mona-color-picker-alpha-wrap" style={{ backgroundImage: CHECKBOARD }}>
            <div className="mona-color-picker-alpha-gradient" style={{ background: `linear-gradient(to right, rgba(${color.r},${color.g},${color.b},0) 0%, rgba(${color.r},${color.g},${color.b},1) 100%)` }} />
            <div
              aria-label="Color opacity"
              className="mona-color-picker-alpha"
              onPointerDown={event => trackPointer(event, (x, _y, rect) => {
                const alpha = Math.round(Math.min(1, Math.max(0, (x - rect.left) / rect.width)) * 100) / 100
                emitRGBA({ ...color, a: alpha })
              })}
              aria-valuemax={100}
              aria-valuemin={0}
              aria-valuenow={Math.round(color.a * 100)}
              role="slider"
              tabIndex={0}
            >
              <span className="mona-color-picker-alpha-pointer" style={{ left: `${color.a * 100}%` }}><span className="mona-color-picker-alpha-picker" /></span>
            </div>
          </div>
        </div>
      </div>

      <div className="mona-color-picker-field">
        <label className="mona-color-picker-hex">
          <span>#</span>
          <input
            aria-label="Hex color"
            onChange={event => {
              if (event.target.value.length < 6) return
              const next = tinycolor(event.target.value)
              if (next.isValid()) emitRGBA(next.toRgb())
            }}
            value={(color.a < 1 ? tinycolor(color).toHex8String() : tinycolor(color).toHexString()).slice(1).toUpperCase()}
          />
        </label>
        <button aria-label="Eyedropper" className="mona-color-picker-eyedropper" onClick={openEyeDropper} type="button"><NeedleIcon /></button>
        <button aria-label="Transparent" className="mona-color-picker-transparent" onClick={() => selectPreset('#00000000')} style={{ backgroundImage: CHECKBOARD }} type="button" />
      </div>

      <div className="mona-color-picker-presets">
        {themeColors.map(item => <PickerSwatch color={item} key={item} onClick={() => selectPreset(item)} />)}
      </div>
      <div className="mona-color-picker-gradients">
        {presetColors.map((column, index) => (
          <div className="mona-color-picker-gradient-column" key={presetColorConfig[index]![0]}>
            {column.map(item => <PickerSwatch color={item} key={item} onClick={() => selectPreset(item)} />)}
          </div>
        ))}
      </div>
      <div className="mona-color-picker-presets">
        {standardColors.map(item => <PickerSwatch color={item} key={item} onClick={() => selectPreset(item)} />)}
      </div>
      {recentColors.length ? <div className="mona-color-picker-recent-title">{t('foundation.editor.colorPicker.recent')}</div> : null}
      <div className="mona-color-picker-presets">
        {recentColors.map(item => <PickerSwatch color={item} key={item} onClick={() => selectPreset(item)} />)}
      </div>
    </div>
  )
}
