import {
  ShapePathFormulasKeys,
  type PPTLineElement,
  type Slide,
} from '@mona/presentation-core/model'
import { SHAPE_PATH_FORMULAS } from '@mona/presentation-core/shape-path-formulas'

const roundRectWidth = 220
const roundRectHeight = 130
const roundRectKeypoints = [0.18]

const line = (
  id: string,
  top: number,
  props: Partial<PPTLineElement> = {},
): PPTLineElement => ({
  id,
  type: 'line',
  left: 90,
  top,
  width: 4,
  start: [0, 0],
  end: [280, 0],
  style: 'solid',
  color: '#22577a',
  points: ['', ''],
  ...props,
})

const editorInteractionSlides: readonly Slide[] = [
  {
    id: 'interaction-resize-fixture',
    background: { type: 'solid', color: '#f7f4ec' },
    elements: [
      {
        id: 'interaction-resize-shape',
        type: 'shape',
        left: 70,
        top: 70,
        width: roundRectWidth,
        height: roundRectHeight,
        rotate: 0,
        fixedRatio: false,
        viewBox: [roundRectWidth, roundRectHeight],
        pathFormula: ShapePathFormulasKeys.ROUND_RECT,
        keypoints: roundRectKeypoints,
        path: SHAPE_PATH_FORMULAS[ShapePathFormulasKeys.ROUND_RECT]!.formula(
          roundRectWidth,
          roundRectHeight,
          roundRectKeypoints,
        ),
        fill: '#80ed99',
        outline: { width: 2, style: 'solid', color: '#22577a' },
      },
      {
        id: 'interaction-resize-image',
        type: 'image',
        left: 360,
        top: 75,
        width: 220,
        height: 130,
        rotate: 0,
        fixedRatio: false,
        src: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='220' height='130'%3E%3Crect width='220' height='130' fill='%23fff3b0'/%3E%3Ccircle cx='110' cy='65' r='42' fill='%23fb8500'/%3E%3C/svg%3E",
      },
      {
        id: 'interaction-rotated-shape',
        type: 'shape',
        left: 680,
        top: 65,
        width: 170,
        height: 140,
        rotate: 45,
        fixedRatio: false,
        viewBox: [170, 140],
        path: 'M 0 0 L 170 0 L 170 140 L 0 140 Z',
        fill: '#ffb703',
      },
      {
        id: 'interaction-horizontal-text',
        type: 'text',
        left: 70,
        top: 310,
        width: 260,
        height: 70,
        rotate: 0,
        content: '<p><span style="font-size: 22px;">Auto-height horizontal text wraps as its width changes.</span></p>',
        defaultFontName: 'Arial',
        defaultColor: '#17324d',
      },
      {
        id: 'interaction-vertical-text',
        type: 'text',
        left: 410,
        top: 270,
        width: 70,
        height: 220,
        rotate: 0,
        vertical: true,
        content: '<p><span style="font-size: 22px;">Vertical auto-width text</span></p>',
        defaultFontName: 'Arial',
        defaultColor: '#17324d',
      },
      {
        id: 'interaction-fixed-text',
        type: 'text',
        left: 570,
        top: 300,
        width: 300,
        height: 130,
        rotate: 0,
        fixedHeight: true,
        vAlign: 'middle',
        content: '<p><span style="font-size: 22px;">Fixed-height text</span></p>',
        defaultFontName: 'Arial',
        defaultColor: '#17324d',
      },
    ],
  },
  {
    id: 'interaction-line-fixture',
    background: { type: 'solid', color: '#ffffff' },
    elements: [
      line('interaction-simple-line', 100),
      line('interaction-broken-line', 210, { broken: [140, 70], end: [280, 20] }),
      line('interaction-broken2-line', 320, { broken2: [140, 55], broken2Direction: 'horizontal', end: [280, 35] }),
      line('interaction-curve-line', 420, { curve: [140, -75], end: [280, 0] }),
      line('interaction-cubic-line', 520, { cubic: [[80, -85], [210, 65]], end: [280, -10] }),
    ],
  },
  {
    id: 'interaction-rotation-fixture',
    background: { type: 'solid', color: '#f4f7fb' },
    elements: [
      {
        id: 'interaction-common-rotation-shape',
        type: 'shape',
        groupId: 'interaction-common-rotation-group',
        left: 90,
        top: 90,
        width: 150,
        height: 110,
        rotate: 30,
        fixedRatio: false,
        viewBox: [150, 110],
        path: 'M 0 0 L 150 0 L 150 110 L 0 110 Z',
        fill: '#8ecae6',
      },
      {
        id: 'interaction-common-rotation-text',
        type: 'text',
        groupId: 'interaction-common-rotation-group',
        left: 310,
        top: 105,
        width: 230,
        height: 80,
        rotate: 30,
        fixedHeight: true,
        content: '<p><span style="font-size: 22px;">Common rotation group</span></p>',
        defaultFontName: 'Arial',
        defaultColor: '#17324d',
      },
      {
        id: 'interaction-line-rotation-shape',
        type: 'shape',
        groupId: 'interaction-line-rotation-group',
        left: 90,
        top: 340,
        width: 150,
        height: 100,
        rotate: 0,
        fixedRatio: false,
        viewBox: [150, 100],
        path: 'M 0 0 L 150 0 L 150 100 L 0 100 Z',
        fill: '#ffb703',
      },
      line('interaction-line-rotation-line', 390, {
        groupId: 'interaction-line-rotation-group',
        left: 320,
        end: [190, 20],
      }),
      {
        id: 'interaction-blocked-rotation-shape',
        type: 'shape',
        groupId: 'interaction-blocked-rotation-group',
        left: 620,
        top: 330,
        width: 120,
        height: 100,
        rotate: 0,
        fixedRatio: false,
        viewBox: [120, 100],
        path: 'M 0 0 L 120 0 L 120 100 L 0 100 Z',
        fill: '#fb8500',
      },
      line('interaction-blocked-rotation-line', 390, {
        groupId: 'interaction-blocked-rotation-group',
        left: 780,
        curve: [70, -65],
        end: [150, 20],
      }),
    ],
  },
]

export const appendEditorInteractionFixture = (slides: readonly Slide[]): Slide[] => {
  const clone = (input: readonly Slide[]) => JSON.parse(JSON.stringify(input)) as Slide[]
  if (slides.some(slide => slide.id === editorInteractionSlides[0]!.id)) return clone(slides)
  return [...clone(slides), ...clone(editorInteractionSlides)]
}
