import type { Slide } from '@mona/presentation-core/model'

const rectanglePath = (width: number, height: number) => `M 0 0 L ${width} 0 L ${width} ${height} L 0 ${height} Z`

const multiElementSlides: readonly Slide[] = [
  {
    id: 'multi-multi-geometry',
    background: { type: 'solid', color: '#f8f5ee' },
    elements: [
      {
        id: 'multi-geometry-rotated',
        type: 'shape',
        left: 70,
        top: 65,
        width: 145,
        height: 95,
        rotate: 31,
        fixedRatio: false,
        viewBox: [145, 95],
        path: rectanglePath(145, 95),
        fill: '#8ecae6',
      },
      {
        id: 'multi-geometry-line',
        type: 'line',
        left: 360,
        top: 90,
        width: 4,
        start: [0, 0],
        end: [165, 48],
        style: 'dashed',
        color: '#22577a',
        points: ['', 'arrow'],
      },
      {
        id: 'multi-geometry-group-shape',
        groupId: 'multi-geometry-group',
        type: 'shape',
        left: 650,
        top: 65,
        width: 115,
        height: 85,
        rotate: -23,
        fixedRatio: false,
        viewBox: [115, 85],
        path: rectanglePath(115, 85),
        fill: '#ffb703',
      },
      {
        id: 'multi-geometry-group-text',
        groupId: 'multi-geometry-group',
        type: 'text',
        left: 790,
        top: 120,
        width: 145,
        height: 64,
        rotate: 0,
        fixedHeight: true,
        content: '<p><span style="font-size: 20px;">Grouped item</span></p>',
        defaultFontName: 'Arial',
        defaultColor: '#17324d',
      },
      {
        id: 'multi-geometry-image',
        type: 'image',
        left: 285,
        top: 375,
        width: 145,
        height: 105,
        rotate: 0,
        fixedRatio: false,
        src: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='145' height='105'%3E%3Crect width='145' height='105' fill='%2390cf5b'/%3E%3Ccircle cx='72.5' cy='52.5' r='30' fill='%23fff'/%3E%3C/svg%3E",
      },
    ],
  },
  {
    id: 'multi-multi-style',
    background: { type: 'solid', color: '#ffffff' },
    elements: [
      {
        id: 'multi-style-text',
        type: 'text',
        left: 35,
        top: 35,
        width: 180,
        height: 65,
        rotate: 0,
        fixedHeight: true,
        content: '<p><span style="font-family: Arial; font-size: 18px; color: #17324d;">Multi text</span></p>',
        defaultFontName: 'Arial',
        defaultColor: '#17324d',
      },
      {
        id: 'multi-style-shape',
        type: 'shape',
        left: 250,
        top: 30,
        width: 170,
        height: 85,
        rotate: 0,
        fixedRatio: false,
        viewBox: [170, 85],
        path: rectanglePath(170, 85),
        fill: '#8ecae6',
        text: {
          content: '<p><span style="font-family: Arial; font-size: 18px; color: #17324d;">Shape text</span></p>',
          defaultFontName: 'Arial',
          defaultColor: '#17324d',
          align: 'middle',
        },
      },
      {
        id: 'multi-style-image',
        type: 'image',
        left: 455,
        top: 30,
        width: 150,
        height: 85,
        rotate: 0,
        fixedRatio: false,
        src: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='150' height='85'%3E%3Crect width='150' height='85' fill='%23f2dbdb'/%3E%3C/svg%3E",
      },
      {
        id: 'multi-style-line',
        type: 'line',
        left: 660,
        top: 75,
        width: 3,
        start: [0, 0],
        end: [150, 0],
        style: 'solid',
        color: '#333333',
        points: ['', ''],
      },
      {
        id: 'multi-style-chart',
        type: 'chart',
        left: 35,
        top: 165,
        width: 270,
        height: 180,
        rotate: 0,
        chartType: 'column',
        data: { labels: ['A', 'B'], legends: ['One', 'Two'], series: [[3, 5], [4, 2]] },
        themeColors: ['#5b9bd5', '#ed7d31'],
      },
      {
        id: 'multi-style-table',
        type: 'table',
        left: 345,
        top: 165,
        width: 270,
        height: 150,
        rotate: 0,
        colWidths: [0.5, 0.5],
        cellMinHeight: 45,
        outline: { width: 2, color: '#525252', style: 'solid' },
        data: [
          [
            { id: 'multi-cell-a', colspan: 1, rowspan: 1, text: '<p>A</p>', style: { color: '#17324d', fontsize: '16px' } },
            { id: 'multi-cell-b', colspan: 1, rowspan: 1, text: '<p>B</p>', style: { color: '#17324d', fontsize: '16px' } },
          ],
          [
            { id: 'multi-cell-c', colspan: 1, rowspan: 1, text: '<p>C</p>', style: { color: '#17324d', fontsize: '16px' } },
            { id: 'multi-cell-d', colspan: 1, rowspan: 1, text: '<p>D</p>', style: { color: '#17324d', fontsize: '16px' } },
          ],
        ],
      },
      {
        id: 'multi-style-latex',
        type: 'latex',
        left: 665,
        top: 190,
        width: 135,
        height: 75,
        rotate: 0,
        latex: 'x^2+y^2',
        path: 'M 5 35 L 40 5 M 5 5 L 40 35 M 55 35 L 90 5 M 55 5 L 90 35',
        color: '#333333',
        strokeWidth: 2,
        viewBox: [100, 40],
        fixedRatio: true,
      },
      {
        id: 'multi-style-audio',
        type: 'audio',
        left: 850,
        top: 200,
        width: 50,
        height: 50,
        rotate: 0,
        fixedRatio: true,
        color: '#5b9bd5',
        loop: false,
        autoplay: false,
        src: 'fixture-audio.mp3',
      },
    ],
  },
]

export const appendMultiElementFixture = (slides: readonly Slide[]): Slide[] => {
  const clone = (input: readonly Slide[]) => JSON.parse(JSON.stringify(input)) as Slide[]
  if (slides.some(slide => slide.id === multiElementSlides[0]!.id)) return clone(slides)
  return [...clone(slides), ...clone(multiElementSlides)]
}
